version: '3.8'

services:
  products-service:
    container_name: products-service
    build:
      context: .
      dockerfile: Dockerfile.products
    environment:
      - SERVER_PORT=4000
      - DATABASE_URI=mongodb://products-database:27017/products
    volumes:
      - "./products-service/:/app/products-service"
    ports:
      - "4000:4000"
    depends_on:
      - products-database
  products-database:
    container_name: products-database
    image: mongo:3.6.21
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=products
    ports:
      - "27017:27017"
    volumes:
      - "./databases/mongodb/db/:/data/db"