version: '3.8'

services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile.products
    environment: 
      - SERVER_PORT=4000
    volumes:
      - "./products-service/:/app/products-service"
    ports:
      - "4000:4000"
