version: '3.8'

services:
###############################################################################
# Reverse Proxy
###############################################################################
  reverse-proxy:
    container_name: nginx-proxy
    restart: unless-stopped
    image: nginx:1.19.6
    ports:
      - "80:80"
    volumes:
      - "./configs/nginx.conf:/etc/nginx/nginx.conf"
      - "./images/:/var/www/images"
    depends_on: 
      - catalog-service
###############################################################################
# Redis Pubsub and cache
###############################################################################
  redis-pubsub:
    container_name: redis-pubsub
    image: redis:6.2-rc2
    restart: unless-stopped
    expose:
      - "6379"
###############################################################################
# Service for the catalog
###############################################################################
  catalog-service: 
    container_name: catalog-service
    build:
      context: .
      dockerfile: ./docker/Dockerfile.catalog
    restart: unless-stopped
    environment:
      - SERVICE_NAME=Catalog
      - SERVER_PORT=4000
      - REDIS_HOST=redis-pubsub
      - REDIS_PORT=6379
      - DATABASE_URI=mongodb://catalog-database:27017/Products
    volumes:
      - "./services/catalog-service/:/app/catalog-service"
      - "./services/utils/:/app/catalog-service/utils/"
    expose:
      - "4000"
    depends_on:
      - catalog-database
  catalog-database:
    container_name: catalog-database
    image: mongo:3.6.21
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=Products
    expose:
      - "27017"
    volumes:
      - "./databases/mongodb/catalog-db/:/data/db"
###############################################################################
# Service for authentication
###############################################################################
  authentication-service: 
    container_name: authentication-service
    build:
      context: .
      dockerfile: ./docker/Dockerfile.authentication
    restart: unless-stopped
    environment:
      - SERVICE_NAME=Authentication
      - SERVER_PORT=4000
      - REDIS_HOST=redis-pubsub
      - REDIS_PORT=6379
      - DATABASE_URI=mongodb://authentication-database:27017/User
    volumes:
      - "./services/authentication-service/:/app/authentication-service"
      - "./services/utils/:/app/authentication-service/utils/"
    expose:
      - "4000"
    depends_on:
      - redis-pubsub
      - authentication-database
  authentication-database:
    container_name: authentication-database
    image: mongo:3.6.21
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=User
    expose:
      - "27017"
    volumes:
      - "./databases/mongodb/authentication-db/:/data/db"
###############################################################################
# Service for shopping
###############################################################################
  shopping-service: 
    container_name: shopping-service
    build:
      context: .
      dockerfile: ./docker/Dockerfile.shopping
    restart: unless-stopped
    environment:
      - SERVICE_NAME=Shopping
      - SERVER_PORT=4000
      - REDIS_HOST=redis-pubsub
      - REDIS_PORT=6379
      - DATABASE_URI=mongodb://shopping-database:27017/Cart
    volumes:
      - "./services/shopping-service/:/app/shopping-service"
      - "./services/utils/:/app/shopping-service/utils/"
    expose:
      - "4000"
    depends_on:
      - redis-pubsub
      - shopping-database
  shopping-database:
    container_name: shopping-database
    image: mongo:3.6.21
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=Cart
    expose:
      - "27017"
    volumes:
      - "./databases/mongodb/shopping-db/:/data/db"