version: '3.8'

services:
  reverse-proxy:
    container_name: nginx-proxy
    restart: unless-stopped
    image: nginx:1.19.6
    ports:
      - "80:80"
    volumes:
      - "./configs/nginx.conf:/etc/nginx/nginx.conf"
      - "./images/:/var/www/images"
    depends_on: 
      - catalog-service
###############################################################################
# Service for the catalog
###############################################################################
  catalog-service: 
    container_name: catalog-service
    build:
      context: .
      dockerfile: ./docker/Dockerfile.catalog
    restart: unless-stopped
    environment:
      - SERVICE_NAME=Catalog
      - SERVER_PORT=4000
      - DATABASE_URI=mongodb://catalog-database:27017/Products
    volumes:
      - "./services/catalog-service/:/app/catalog-service"
    expose:
      - "4000"
    depends_on:
      - catalog-database
  catalog-database:
    container_name: catalog-database
    image: mongo:3.6.21
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=Products
    expose:
      - "27017"
    volumes:
      - "./databases/mongodb/catalog-db/:/data/db"
###############################################################################
# Service for authentication
###############################################################################
  authentication-service: 
    container_name: authentication-service
    build:
      context: .
      dockerfile: ./docker/Dockerfile.authentication
    restart: unless-stopped
    environment:
      - SERVICE_NAME=Authentication
      - SERVER_PORT=4000
      - DATABASE_URI=mongodb://authentication-database:27017/User
    volumes:
      - "./services/authentication-service/:/app/authentication-service"
    expose:
      - "4000"
    depends_on:
      - authentication-database
  authentication-database:
    container_name: authentication-database
    image: mongo:3.6.21
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=User
    expose:
      - "27017"
    volumes:
      - "./databases/mongodb/authentication-db/:/data/db"