export const SHOPPING_ADD = 'SHOPPING_ADD';
export const SHOPPING_REMOVE = 'SHOPPING_REMOVE';
export const SHOPPING_REMOVE_ALL = 'SHOPPING_REMOVE_ALL';

export const READ_SHIPPING_INFO_REQUEST = 'READ_SHIPPING_INFO_REQUEST';
export const READ_SHIPPING_INFO_SUCCESS = 'READ_SHIPPING_INFO_SUCCESS';
export const READ_SHIPPING_INFO_FAIL = 'READ_SHIPPING_INFO_FAIL';

export const UPDATE_SHIPPING_INFO_REQUEST = 'UPDATE_SHIPPING_INFO_REQUEST';
export const UPDATE_SHIPPING_INFO_SUCCESS = 'UPDATE_SHIPPING_INFO_SUCCESS';
export const UPDATE_SHIPPING_INFO_FAIL = 'UPDATE_SHIPPING_INFO_FAIL';