export const SHOPPING_ADD_REQUEST = 'SHOPPING_ADD_REQUEST';
export const SHOPPING_ADD_SUCCESS = 'SHOPPING_ADD_SUCCESS';
export const SHOPPING_ADD_FAIL = 'SHOPPING_ADD_FAIL';

export const SHOPPING_READ_REQUEST = 'SHOPPING_READ_REQUEST';
export const SHOPPING_READ_SUCCESS = 'SHOPPING_READ_SUCCESS';
export const SHOPPING_READ_FAIL = 'SHOPPING_READ_FAIL';
export const SHOPPING_READ_RESET = 'SHOPPING_READ_RESET';

export const SHOPPING_REMOVE_REQUEST = 'SHOPPING_REMOVE_REQUEST';
export const SHOPPING_REMOVE_SUCCESS = 'SHOPPING_REMOVE_SUCCESS';
export const SHOPPING_REMOVE_FAIL = 'SHOPPING_REMOVE_FAIL';

export const SHOPPING_REMOVE_ALL_REQUEST = 'SHOPPING_REMOVE_ALL_REQUEST';
export const SHOPPING_REMOVE_ALL_SUCCESS = 'SHOPPING_REMOVE_ALL_SUCCESS';
export const SHOPPING_REMOVE_ALL_FAIL = 'SHOPPING_REMOVE_ALL_FAIL';

export const READ_SHIPPING_INFO_REQUEST = 'READ_SHIPPING_INFO_REQUEST';
export const READ_SHIPPING_INFO_SUCCESS = 'READ_SHIPPING_INFO_SUCCESS';
export const READ_SHIPPING_INFO_FAIL = 'READ_SHIPPING_INFO_FAIL';

export const UPDATE_SHIPPING_INFO_REQUEST = 'UPDATE_SHIPPING_INFO_REQUEST';
export const UPDATE_SHIPPING_INFO_SUCCESS = 'UPDATE_SHIPPING_INFO_SUCCESS';
export const UPDATE_SHIPPING_INFO_FAIL = 'UPDATE_SHIPPING_INFO_FAIL';