FROM node:15.5.1-alpine3.10
WORKDIR /app
COPY ../package*.json /app/
RUN npm install package.json
COPY ../services/shopping-service/ /app/shopping-service
COPY ../services/utils/ /app/shopping-service/utils/
COPY ../configs/.env /app/
EXPOSE 4000
CMD ["npm", "run", "start-shopping-service"]